// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

String webApiKey = dotenv.env['WEB_API_KEY'] ?? "";
String webAppId = dotenv.env["WEB_APP_ID"] ?? "";

String androidApiKey = dotenv.env["ANDROID_API_KEY"] ?? "";
String androidAppId = dotenv.env["ANDROID_APP_ID"] ?? "";

String iosApiKey = dotenv.env["IOS_API_KEY"] ?? "";
String iosAppId = dotenv.env["IOS_APP_ID"] ?? "";
String iosClientId = dotenv.env["IOS_CLIENT_ID"] ?? "";

String messageSenderId = dotenv.env["MESSAGE_SENDER_ID"] ?? "";
String projectId = dotenv.env["PROJECT_ID"] ?? "";
String storageBucket = dotenv.env["STORAGE_BUCKET"] ?? "";

String macApiKey = dotenv.env["MAC_API_KEY"] ?? "";

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: webApiKey,
    appId: webAppId,
    messagingSenderId: messageSenderId,
    projectId: projectId,
    authDomain: 'simpliifitness.firebaseapp.com',
    storageBucket: storageBucket,
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: androidApiKey,
    appId: androidAppId,
    messagingSenderId: messageSenderId,
    projectId: projectId,
    storageBucket: storageBucket,
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: iosApiKey,
    appId: iosAppId,
    messagingSenderId: messageSenderId,
    projectId: projectId,
    storageBucket: storageBucket,
    iosClientId: iosClientId,
    iosBundleId: 'com.example.simpliiFitness',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: macApiKey,
    appId: iosAppId,
    messagingSenderId: messageSenderId,
    projectId: projectId,
    storageBucket: storageBucket,
    iosClientId: iosClientId,
    iosBundleId: 'com.example.simpliiFitness',
  );
}
